extends: airbnb-base
parser: "@typescript-eslint/parser"
plugins: ['@typescript-eslint', 'prettier']
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
rules:
  lines-between-class-members: 0
  no-param-reassign: ["error", { "props": false }]
  no-else-return: 0
  no-underscore-dangle: 0
  nonblock-statement-body-position: 0
  curly: 0
  no-return-assign: 0
  consistent-return: 0
  no-mixed-operators: 0
  class-methods-use-this: 0
  no-nested-ternary: 0
  camelcase: 0
  no-unused-vars: 0
  import/no-unresolved: 0
  no-inner-declarations: 0
  arrow-body-style: 0
  operator-linebreak: 0
  import/prefer-default-export: 0
  import/extensions: 0
  new-cap: ["error", { "newIsCap": false }]
  max-len: ["error", {"code": 120, "ignoreUrls": true}]
  indent: ["error", 2, {"FunctionDeclaration": {"parameters": "first"}, "ArrayExpression": "first"}]
globals:
  document: true
  window: true
  Event: true
  customElements: true
